### ISSUE TITLE
Add support for Mac host

### ISSUE THREAD

**Issue by ahumesky** [bazelbuild/rules_android_ndk#1]
`android_ndk_repository` in `rules.bzl` is currently hard-coded for Linux.

**Comment by cpsauer** [comment]
Thanks so much @ahumesky!
[Subscribing and will play around more just as soon as this lands.]

**Comment by keith** [comment]
@ahumesky is this something you're planning on picking up or should someone from the community take it on?

**Comment by keith** [comment]
❤️

**Comment by ahumesky** [comment]
It looks like all that was needed was to select the right clang directory, and the host_system_name is no longer used, so that could just be deleted. I can build the example app on both linux and mac now.
