### ISSUE TITLE
Cross compilation issues

### ISSUE THREAD

**Issue by oakad** [bazelbuild/rules_android_ndk#19]
Bazel version 5.2.0, Linux, commit 81ec8b79dc50ee97e336a25724fdbb28e33b8d41 (as advertised)

I tried to build some project for an emulator. It appears to be impossible to run qemu based ARM64 emulator on Linux these days (it behaves rather weirdly and goes nowhere), so I wanted to use an AMD64 emulator, to the tune of:

> bazel build --android_crosstool_top=@androidndk//:toolchain --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cxxopt=-std=c++17 --cpu=x86_64 --fat_apk_cpu=x86_64 //target

This failed with an error:
> .../external/local_config_cc/BUILD:47:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'x86_64'

Am I doing something wrong or is it not supported just yet?

I don't really need AMD64 support, so if there's some advice regarding running an ARM64 emulator on AMD64 it will be handy as well.

**Comment by ahumesky** [comment]
The immediate issue here is that `--cpu=x86_64` is used with `--crosstool_top` with its default value (`@bazel_tools//tools/cpp:toolchain` which is an alias for `@local_config_cc//:toolchain`), and the default toolchain doesn't have a cpu named `x86_64` (the default toolchain uses `k8` for x86-64).

The way to address this depends on what you're building:

If you're building an `android_binary` target with `cc_library` targets in its dependencies, then just take out `--cpu=x86_64`. The `android_binary` target will read `--fat_apk_cpu` for compiling the `cc_library` targets in its dependencies. (It's also not necessary to set `--host_crosstool_top` in this scenario.)

If you're building `cc_binary` or `cc_library` targets independently of an `android_binary` target, then set ` --crosstool_top=@androidndk//:toolchain`, and `--cpu` to the desired cpu. `--android_crosstool_top` and `--fat_apk_cpu` will be ignored.

Note that there are some interactions here with target patterns like `//...`. If you have an `android_binary` with `cc_library` targets in its dependencies, then `//...` will build the `cc_library` as both a top-level target, which will use `--crosstool_top` and `--cpu`, and as a dependency of an `android_binary`, which will use `--android_crosstool_top` and `--fat_apk_cpu`. We fell for this ourselves here: https://github.com/bazelbuild/rules_android_ndk/commit/2a3c13bd1132fc3f697856aea570ba3386d0e5cb

**Comment by oakad** [comment]
A related question: what is the correct approach to select a variant within the `select` construct? 

`rules_apple` define a whole bunch of "cpu" derived config settings ( https://github.com/bazelbuild/rules_apple/blob/1b42c9f8d2467554eaa49ac80a50cafd2a2507d4/apple/BUILD#L10 ) which then can be handily used to select things:
```
 src = select({
        ":ios_x86_64": "foo",
        ":ios_armv7": "bar",
})
```

How shall I achieve the same effect with `rules_android_ndk`?
(I could not figure a safe way to this with old NDK rules either and had to come with a bunch of a custom `define` flags).

**Comment by ahumesky** [comment]
Ideally the canonical platforms here would work: https://github.com/bazelbuild/platforms
however the android rules haven't been fully migrated to platforms yet, see https://github.com/bazelbuild/bazel/issues/16285
(though it's possible to bridge this with platform mappings: https://bazel.build/concepts/platforms#platform-mappings).

The next best thing is to define config_settings and use those directly:

```
config_setting(
  name = "x86_64",
  values = {"cpu": "x86_64"},
)

config_setting(
  name = "arm64-v8a",
  values = {"cpu": "arm64-v8a"},
)

cc_library(
    name = "jni",
    srcs = ["jni.cc"],
    deps = select({
      "@platforms//cpu:x86_64": [":jni_dep_x86_64"],
      "@platforms//cpu:arm64": [":jni_dep_arm64"],
    }),
)

cc_library(
    name = "jni_dep_x86_64",
    srcs = ["jni_dep_x86_64.cc"],
    hdrs = ["jni_dep.h"],
)

cc_library(
    name = "jni_dep_arm64",
    srcs = ["jni_dep_arm64.cc"],
    hdrs = ["jni_dep.h"],
)
```

**Comment by ahumesky** [comment]
Some years ago I was similarly frustrated with "what cpus can I use":
https://github.com/bazelbuild/bazel/commit/6cfa830c0d11e9bd7908bd0182db95454e5b258b
however I think that's been refactored out of existence.

What errors are you getting after trying https://github.com/bazelbuild/rules_android_ndk/issues/19#issuecomment-1251257261 ?

**Comment by oakad** [comment]
> android_binary target with cc_library targets in its dependencies, then just take out --cpu=x86_64

If I take it out, the relevant `config_setting` is not selected.

**Comment by ahumesky** [comment]
That suggests that you're building something other than an `android_binary` target, or something in addition to the `android_binary` target. Can you share more complete repro steps?

android_binary takes `--fat_apk_cpu` and `--android_crosstool_top` and translates them into `--cpu` and `--crosstool_top` for each cpu in `--fat_apk_cpu` for its dependencies (i.e., you get multiple versions of the `cc_library` targets in its deps). That's why `cpu` is listed in the `config_setting`s. However, if there are other targets that are getting built as top-level targets (i.e. explicitly listed on the command line, or built through a target pattern like `//...` or `//pkg:all`) then they get the "regular" top-level values of `--cpu` and `--crosstool_top`. So that suggests that there are other targets that are not in the deps of an `android_binary` that are getting the "android" value of `--cpu`, but not the "android" value of `--crosstool_top`.

**Comment by oakad** [comment]
My project is cross platform - the same project should build for android, apple and linux/windows. There are multiple selectors for things, depending on CPU and OS.
With the old rules, I used the following selector to cover the Android os:
```
config_setting(
    name = "android_ndk",
    values = {
        "crosstool_top": "@androidndk//:default_crosstool",
    },
)
```
This, combined with CPU config settings sort of worked for selecting Android on the both CPUs I need.

With the present toolchain, I'm not yet sure how to proceed short of defining a custom, explicit `define`.

**Comment by oakad** [comment]
I will close this as I think I have figured out a decent enough mix of `config_setting` and patches to dependencies to work for me.
