### ISSUE TITLE
Add support for Windows host

### ISSUE THREAD

**Issue by ahumesky** [bazelbuild/rules_android_ndk#2]
`android_ndk_repository` in `rules.bzl` is currently hard-coded for Linux.

**Comment by oakad** [comment]
I've got one of my project compiling fine with rules_android_ndk on Linux and now want to do so on Windows. Alas, as of right now it's still "Unsupported operating system: windows 10".

If something happens in the Windows support direction, I will be happy to test whatever changes are there. :-)

**Comment by oakad** [comment]
Windows is still the most used platform by Android devs (AFAIK). By having NDK broken on Bazel/Windows (as people keep upgrading their NDKs), you're essentially telling us to drop Bazel and go look elsewhere.

The ongoing campaign of closing all the old Bazel issues without ever fixing most of them is also not encouraging trust. :-)

**Comment by master-hax** [comment]
+1 interested in Windows support

**Comment by marcushultman** [comment]
I must be missing something, but it seems like I can't even use this repository_rule since I need to be able to configure my WORKSPACE on multiple platforms (including windows). Even if no target depend on the repository, the whole setup errors out when configuring. How can optionally call `android_ndk_repository` based on platform from my WORKSPACE?

**Comment by ahumesky** [comment]
In preparation for this, an updated NDK needs to be added with the Windows BazeCI image: https://github.com/bazelbuild/continuous-integration/issues/1962

**Comment by ahumesky** [comment]
@marcushultman see https://stackoverflow.com/questions/78122191/bazel-its-possible-to-download-different-external-dependencies-depending-on-the for some advice on making this work across different platforms

**Comment by oakad** [comment]
These news are most welcome. :-)
