### ISSUE TITLE
Don't create BUILD files in the NDK installation directory

### ISSUE THREAD

**Issue by ahumesky** [bazelbuild/rules_android_ndk#3]
For simplicity, the top-level `toolchains` directory of the NDK is symlinked into the external repository directory, but this means that when `android_ndk_repository` creates BUILD files, they're created in the real NDK installation directory: 

https://github.com/bazelbuild/rules_android_ndk/blob/631ba9afc76862ed3aa715ec292c03ed2724a3e0/rules.bzl#L61

https://github.com/bazelbuild/rules_android_ndk/blob/631ba9afc76862ed3aa715ec292c03ed2724a3e0/rules.bzl#L76

**Comment by keith** [comment]
I think this also impacts development with the templates, I believe it's because of this that sometimes when I'm using `--override_repository` with this repo you get some invalid syntax issues that re-running bazel fixes, I haven't debugged further

**Comment by ahumesky** [comment]
Looks like this is blocking allowing us to use bazelci, since the ndk is mounted someplace read-only:
https://github.com/bazelbuild/rules_android_ndk/issues/12#issuecomment-1241637280
