### ISSUE TITLE
How to correctly link to liblog?

### ISSUE THREAD

**Issue by fernand** [bazelbuild/rules_android_ndk#38]
I have a project using the latest android_ndk_repository with NDK 25. 

Everything builds fine, including large third party dependencies. I’m however unable to link to liblog.so, even when passing ‘-llog’, in which case lld can’t find the library.

if I revert to using the builtin Bazel NDK rule and NDK 21, the problem goes away.

**Comment by jiawen** [comment]
Can you share a repro or a snippet? It's encouraging that it's working in ndk 21.
