### ISSUE TITLE
Auto-detect clang version

### ISSUE THREAD

**Issue by ahumesky** [bazelbuild/rules_android_ndk#4]
The version of clang is hardcoded:
https://github.com/bazelbuild/rules_android_ndk/blob/631ba9afc76862ed3aa715ec292c03ed2724a3e0/rules.bzl#L40

and it might be easy to auto-detect the clang resource directory (especially if there will only ever be one of them)

**Comment by cpsauer** [comment]
To auto detect, we need to exec an external tool, right, since there's no directory list function on a repository_ctx?

**Comment by cpsauer** [comment]
Took a shot at this in #29 :)
