### ISSUE TITLE
Is Android NDK r25c support?

### ISSUE THREAD

**Issue by RookieTars** [bazelbuild/rules_android_ndk#57]
Accord to README,  rules in this repo currently work with **Android NDK version 25b** , but I can't find download url of NDK 25b. 

1. However, **NDK r25c** is accessible. Is r25c supported? Or is there anything I should pay attention to while using r25c?

2. Providing download url of NDK 25b is also thankful.

Thanks!

**Comment by keith** [comment]
It seems that the `b` -> `c` type updates are generally pretty small, so I think `r25c` should work just fine as well. Please file any issues you find if not.

Looking at the URLs for the r25c downloads like this one:

https://dl.google.com/android/repository/android-ndk-r25c-darwin.dmg

Replacing `c` with `b` seems to work still. It seems like the recommendation from the NDK docs is to upgrade though, so they must have pulled those URLs from the docs

**Comment by RookieTars** [comment]
Thanks a lot.

**Comment by DanAlbert** [comment]
Any time an NDK minor version upgrade breaks compatibility with a build system, that's more likely an NDK bug.
